const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const API_KEY='bonescan_api_base';
let apiBase=localStorage.getItem(API_KEY)||'';
const toast=(msg)=>{const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2600)};
const scrollTo=(id)=>$(id)?.scrollIntoView({behavior:'smooth',block:'start'});
$$('[data-scroll]').forEach(b=>b.addEventListener('click',()=>scrollTo(b.dataset.scroll)));
const menuBtn=$('#menuBtn'),nav=$('#nav');menuBtn?.addEventListener('click',()=>{nav.classList.toggle('open');menuBtn.textContent=nav.classList.contains('open')?'×':'☰'});$$('nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
window.addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;$('#progress').style.width=(h>0?scrollY/h*100:0)+'%'});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});$$('.reveal').forEach(e=>observer.observe(e));
function updateApiState(){const configured=Boolean(apiBase);$('#heroApi').textContent=configured?'CONNECTED':'NOT SET';$('#heroApi').style.color=configured?'var(--cyan)':'#8ba0b4'}updateApiState();
const dialog=$('#settingsDialog'),apiInput=$('#apiInput'),settingsBtn=$('#settingsBtn');settingsBtn.addEventListener('click',()=>{apiInput.value=apiBase;dialog.showModal()});
$('#saveApi').addEventListener('click',e=>{e.preventDefault();apiBase=apiInput.value.trim().replace(/\/$/,'');if(apiBase)localStorage.setItem(API_KEY,apiBase);else localStorage.removeItem(API_KEY);updateApiState();dialog.close();toast(apiBase?'Backend connection saved':'Backend connection cleared')});
const modelSelect=$('#modelSelect'),heroModel=$('#heroModel');$$('.choose-model').forEach(b=>b.addEventListener('click',()=>{modelSelect.value=b.dataset.model;heroModel.textContent=b.dataset.model==='cnn'?'CNN':b.dataset.model==='svm'?'SVM':b.dataset.model==='logistic'?'LOGISTIC':'FOREST';scrollTo('#predict');toast(`${heroModel.textContent} selected`)}));modelSelect.addEventListener('change',()=>{heroModel.textContent=modelSelect.options[modelSelect.selectedIndex].text.split(' —')[0]});
const input=$('#fileInput'),drop=$('#dropzone'),preview=$('#preview'),empty=$('#emptyState'),analyze=$('#analyzeBtn'),clear=$('#clearBtn'),overlay=$('#scanOverlay'),note=$('#consoleNote');let file=null;
function setFile(f){if(!f)return;if(!f.type.startsWith('image/')){toast('Please choose a JPG, JPEG or PNG image.');return}file=f;preview.src=URL.createObjectURL(f);drop.classList.add('has-image');analyze.disabled=false;note.textContent=`Ready: ${f.name} · ${(f.size/1024/1024).toFixed(2)} MB`;resetResult()}
input.addEventListener('change',e=>setFile(e.target.files[0]));$('#browseBtn').addEventListener('click',e=>{e.stopPropagation();input.click()});drop.addEventListener('click',e=>{if(e.target.closest('button'))return;if(!file)input.click()});['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('drag') }));drop.addEventListener('drop',e=>setFile(e.dataTransfer.files[0]));
function resetResult(){$('#resultEmpty').hidden=false;$('#resultContent').hidden=true;$('#resultState').textContent='WAITING'}
clear.addEventListener('click',()=>{file=null;input.value='';preview.removeAttribute('src');drop.classList.remove('has-image');analyze.disabled=true;note.textContent='No image selected. Upload an X-ray to begin.';resetResult()});
async function analyzeImage(){if(!file)return;if(!apiBase){toast('Connect a Flask API in Settings first.');dialog.showModal();return}analyze.disabled=true;overlay.classList.add('active');note.textContent='Uploading image and waiting for backend response…';$('#resultState').textContent='RUNNING';const form=new FormData();form.append('file',file);form.append('model',modelSelect.value);try{const res=await fetch(`${apiBase}/predict`,{method:'POST',body:form});let data={};try{data=await res.json()}catch{throw new Error('Backend returned a non-JSON response.')}if(!res.ok)throw new Error(data.error||`Prediction request failed (${res.status}).`);renderResult(data);note.textContent='Backend response received successfully.'}catch(err){note.textContent=err.message;$('#resultState').textContent='ERROR';toast(err.message)}finally{overlay.classList.remove('active');analyze.disabled=false}}
analyze.addEventListener('click',analyzeImage);
function renderResult(data){$('#resultEmpty').hidden=true;$('#resultContent').hidden=false;$('#resultState').textContent='RECEIVED';const label=data.label||data.prediction||data.result||'Prediction returned';$('#resultLabel').textContent=label;const c=data.confidence??data.confidence_score??data.probability;$('#confidenceValue').textContent=c==null?'—':`${Number(c)<=1?Number(c)*100:Number(c).toFixed(2)}%`;$('#resultModel').textContent=(data.model||modelSelect.value).toString().toUpperCase();$('#resultMessage').textContent=data.disclaimer||data.message||'Backend response displayed as returned. Clinical interpretation is required.';const positive=/cancer|positive|malignan/i.test(label);$('#resultIcon').textContent=positive?'!':'✓';$('#resultIcon').style.color=positive?'var(--danger)':'var(--cyan)';$('#resultIcon').style.borderColor=positive?'rgba(255,109,120,.35)':'rgba(71,230,211,.35)'}
// Keep the UI honest: no simulated medical predictions are generated client-side.
console.info('BoneScan AI static frontend ready. Configure the Flask API in Settings to enable real inference.');
